### ISSUE TITLE
formatSpec treated as comment

### ISSUE THREAD

**Issue by an4s** [Jubobs/matlab-prettifier#1]
`%` characters in `formatSpec` of `fprintf` function are treated as comments whereas they should be treated as string. Furthermore, the `formatSpec` string is not colored as how a string is usually colored. I have attached the corresponding output in Latex for the MATLAB code below.

`disp('This is how strings should be treated!');
fprintf("This is a string with %s.\n", "a variable input");`
![image](https://user-images.githubusercontent.com/31782645/38764182-01b9ba7a-3f78-11e8-8bab-9fb97ff375cb.png)

**Comment by jubobs** [comment]
Sorry for not getting back to you earlier...

MATLAB strings are delimited by single quotes (`'`). Why are you using double quotes (`"`) for the `formatSpec` string here? Did you just make a mistake? if I use single quotes, I get the expected output:

```latex
\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[framed,numbered]{matlab-prettifier}

\begin{document}
\begin{lstlisting}[
  style      = Matlab-editor,
  basicstyle = \mlttfamily,
]
disp('This is how strings should be treated!');
fprintf('This is a string with %s.\n', 'a variable input');
\end{lstlisting}
\end{document}
```

![screen shot 2018-11-26 at 23 32 46](https://user-images.githubusercontent.com/7138892/49046250-bf057700-f1d3-11e8-910d-7c074381aaca.png)
