### ISSUE TITLE
symbolic variables do not appear in magenta in definition

### ISSUE THREAD

**Issue by unamunoe** [Jubobs/matlab-prettifier#2]
When defining symbolic variables, the names should appear in magenta as follows:
![image](https://user-images.githubusercontent.com/10604465/48887990-84958600-ee31-11e8-8629-1246901d9ef1.png)

However, the output of this code with the matlab-prettifier package looks as follows:
![image](https://user-images.githubusercontent.com/10604465/48888053-b73f7e80-ee31-11e8-929d-23854c943fa1.png)

**Comment by jubobs** [comment]
matlab-prettifier currently only offers partial support for unquoted strings (see section 8 of [the documentation](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/matlab-prettifier/matlab-prettifier.pdf)). Providing further support for them appears quite difficult, and I have no plans to do so in the near future. Sorry.

If you can figure out a way to fix this, though, you're welcome to create a pull request.
